### ISSUE TITLE
How can I use implementations?

### ISSUE THREAD

**Issue by Sisimoski** [ashwin003/RadioBrowser.Net#1]
I have no idea how can I use your wrapper in my project. Could you give some examples, please?

**Comment by ashwin003** [comment]
@Sisimoski Sure Thing. I'll add a sample project to this repo soon.

**Comment by ashwin003** [comment]
@Sisimoski Added a sample console application and updated the README. Please let me know if this helps.

**Comment by Sisimoski** [comment]
@ashwin003 Yes, now I know how to use it. Thanks for the explanation!
